import { MOTIVO_TRAMITE } from "./sistemaConfig";

export const CAMPOS_LOGIN = {
  USUARIO: "txtUsuario",
  CONTRASENA: "txtContrasena",
  RECORDARME: "cboRecordarme",
};

export const CAMPOS_EMPLEADO = {
  ID_EMPLEADO: "idEmpleado",
  NOMBRES: "nombres",
  APELLIDO_PATERNO: "apellidoPaterno",
  APELLIDO_MATERNO: "apellidoMaterno",
  HOMBRE: "hombre",
  FECHA_NACIMIENTO: "fechaNacimiento",
  RFC: "rfc",
  NACIONALIDAD: "nacionalidad",
  USUARIO: "usuario",
  CONTRASENA_ACTUAL: "contrasenaActual",
  CONTRASENA_NUEVA: "contrasenaNueva",
  CONFIRMAR_CONTRASENA: "confirmarContrasena",
  EMAIL: "email",
  TELEFONO: "telefono",
  ROL: "rol",
  PERMISOS: "permisos",
  FECHA_INGRESO: "fechaIngreso",
  NOMBRAMIENTO: "nombramiento",
  ACTIVO: "activo",
  FECHA_CREACION: "fechaCreacion",
  FECHA_MODIFICACION: "fechaModificacion",
};

export const CAMPOS_CARACTERISTICA = {
  ID_CARACTERISTICA: "txtIdCaracteristicaBien",
  FAMILIA: "slcFamilia",
  SUBFAMILIA: "slcSubfamilia",
  ETIQUETA: "txtEtiqueta",
  DESCRIPCION: "txtDescripcion",
  ACTIVO: "cboActivo",
  FECHA_CREACION: "txtFechaCreacion",
  FECHA_MODIFICACION: "txtFechaModificacion",
};

export const CAMPOS_DOCUMENTO = {
  ID_DOCUMENTO: "idDocumento",
  NOMBRE: "nombre",
  ABREVIACION: "abreviacion",
  SUB_MODULO: "subModulo",
  TIPO_TRAMITE: "tipoTramite",
  MOTIVO_TRAMITE: "motivoTramite",
  FECHA_CREACION: "fechaCreacion",
  FECHA_MODIFICACION: "fechaModificacion",
  ACTIVO: "activo",
};

export const CAMPOS_CENTRO_TRABAJO = {
  ID_CENTRO_TRABAJO: "idCentroTrabajo",
  PERIODO: "Periodo",
  CLAVE: "Clave",
  NOMBRE: "NOMBRE",
  DIRECCION: "DIRECCION",
  MUNICIPIO: "MUNICIPIO",
  UNIDAD_ADMINISTRATIVA: "UNIDAD_ADMINISTRATIVA",
  ACTIVO: "activo",
  FECHA_CREACION: "fechaCreacion",
  FECHA_MODIFICACION: "fechaModificacion",
};

export const CAMPOS_CENTRO_TRABAJO_TURNO = {
  ID_CENTRO_TRABAJO_TURNO: "idCentroTrabajoTurno",
  CENTRO_TRABAJO: "idCentroTrabajo",
  TURNO: "idTurno",
  FECHA_CREACION: "fechaCreacion",
  FECHA_MODIFICACION: "fechaModificacion",
  ACTIVO: "activo",
};

export const CAMPOS_CLASE_VEHICULAR = {
  ID_CLASE_VEHICULAR: "txtIdClaseVehicular",
  NOMBRE: "nombre",
  DESCRIPCION: "descripcion",
  FECHA_CREACION: "fechaCreacion",
  FECHA_MODIFICACION: "fechaModificacion",
  ACTIVO: "activo",
};

export const CAMPOS_CLAVE_VEHICULAR = {
  ID_CLAVE_VEHICULAR: "idClaveVehicular",
  NOMBRE: "nombre",
  DESCRIPCION: "descripcion",
  FECHA_CREACION: "fechaCreacion",
  FECHA_MODIFICACION: "fechaModificacion",
  ACTIVO: "activo",
};

export const CAMPOS_COLOR = {
  ID_COLOR: "idColor",
  NOMBRE: "nombre",
  CODIGO_RGB: "codigoRGB",
  FECHA_CREACION: "fechaCreacion",
  FECHA_MODIFICACION: "fechaModificacion",
  ACTIVO: "activo",
};

export const CAMPOS_COMBUSTIBLE = {
  ID_COMBUSTIBLE: "idCombustibleVehicular",
  NOMBRE: "nombre",
  DESCRIPCION: "descripcion",
  FECHA_CREACION: "fechaCreacion",
  FECHA_MODIFICACION: "fechaModificacion",
  ACTIVO: "activo",
};

export const CAMPOS_ESTADO_FISICO = {
  ID_ESTADO_FISICO: "idEstadoFisico",
  NOMBRE: "nombre",
  DESCRIPCION: "descripcion",
  FECHA_CREACION: "fechaCreacion",
  FECHA_MODIFICACION: "fechaModificacion",
  ACTIVO: "activo",
};

export const CAMPOS_ESTADO_GENERAL = {
  ID_ESTADO_GENERAL: "idEstadoGeneral",
  NOMBRE: "nombre",
  FECHA_CREACION: "fechaCreacion",
  FECHA_MODIFICACION: "fechaModificacion",
  ACTIVO: "activo",
};

export const CAMPOS_FAMILIA = {
  ID_FAMILIA: "idFamilia",
  TIPO_BIEN: "tipoBien",
  NOMBRE: "nombre",
  DESCRIPCION: "descripcion",
  FECHA_CREACION: "fechaCreacion",
  FECHA_MODIFICACION: "fechaModificacion",
  ACTIVO: "activo",
};

export const CAMPOS_LINEA_VEHICULAR = {
  ID_LINEA_VEHICULAR: "idLineaVehicular",
  NOMBRE: "nombre",
  DESCRIPCION: "descripcion",
  FECHA_CREACION: "fechaCreacion",
  FECHA_MODIFICACION: "fechaModificacion",
  ACTIVO: "activo",
};

export const CAMPOS_MARCA = {
  ID_MARCA: "idMarca",
  NOMBRE: "nombre",
  OBSERVACIONES: "observaciones",
  FECHA_CREACION: "fechaCreacion",
  FECHA_MODIFICACION: "fechaModificacion",
  ACTIVO: "activo",
};

export const CAMPOS_ORIGEN_VALOR = {
  ID_ORIGEN_VALOR: "idOrigenValor",
  ORIGEN: "origen",
  DESCRIPCION: "descripcion",
  FECHA_CREACION: "fechaCreacion",
  FECHA_MODIFICACION: "fechaModificacion",
  ACTIVO: "activo",
};

export const CAMPOS_SUBFAMILIA = {
  ID_SUBFAMILIA: "idSubfamilia",
  FAMILIA: "familia",
  NOMBRE: "nombre",
  DESCRIPCION: "descripcion",
  VALOR_RECUPERABLE: "valorRecuperable",
  FECHA_CREACION: "fechaCreacion",
  FECHA_MODIFICACION: "fechaModificacion",
  ACTIVO: "activo",
};

export const CAMPOS_TIPO_ADQUISICION = {
  ID_TIPO_ADQUISICION: "idTipoAdquisicion",
  NOMBRE: "nombre",
  FECHA_CREACION: "fechaCreacion",
  FECHA_MODIFICACION: "fechaModificacion",
  ACTIVO: "activo",
};

export const CAMPOS_TIPO_AFECTACION = {
  ID_TIPO_AFECTACION: "idTipoAfectacion",
  NOMBRE: "nombre",
  FECHA_CREACION: "fechaCreacion",
  FECHA_MODIFICACION: "fechaModificacion",
  ACTIVO: "activo",
};

export const CAMPOS_TIPO_BIEN = {
  ID_TIPO_BIEN: "idTipoBien",
  NOMBRE: "nombre",
  DESCRIPCION: "descripcion",
  FECHA_CREACION: "fechaCreacion",
  FECHA_MODIFICACION: "fechaModificacion",
  ACTIVO: "activo",
};

export const CAMPOS_TIPO_INMUEBLE = {
  ID_TIPO_INMUEBLE: "idTipoInmueble",
  NOMBRE: "nombre",
  DESCRIPCION: "descripcion",
  FECHA_CREACION: "fechaCreacion",
  FECHA_MODIFICACION: "fechaModificacion",
  ACTIVO: "activo",
};

export const CAMPOS_TIPO_VEHICULAR = {
  ID_TIPO_VEHICULAR: "idTipoVehicular",
  NOMBRE: "nombre",
  DESCRIPCION: "descripcion",
  FECHA_CREACION: "fechaCreacion",
  FECHA_MODIFICACION: "fechaModificacion",
  ACTIVO: "activo",
};

export const CAMPOS_RESGUARDNATE = {
  ID_RESGUARDNATES: "idResguardante",
  PERIODO: "periodo",
  PERSONA: "persona",
  UNIDAD_ADMINISTRATIVA: "unidadAdminstrativa",
  OBSERVACIONES: "observaciones",
  NO_CONVENIO: "noConvenio",
  TIPO_RESPONSABLE: "tipoResponsable",
  RESPONSABLE: "responsable",
  FECHA_CREACION: "fechaCreacion",
  FECHA_MODIFICACION: "fechaModificacion",
  ACTIVO: "activo",
};

export const CAMPOS_TITULAR = {
  ID_TITULAR: "idTitular",
  NOMBRE: "nombre",
  CENTRO_TRABAJO_TURNO: "centroTrabajoTurno",
  CENTRO_TRABAJO: "centroTrabajo",
  TURNO: "turno",
  FECHA_CREACION: "fechaCreacion",
  FECHA_MODIFICACION: "fechaModificacion",
  ACTIVO: "activo",
};

export const CAMPOS_TURNO = {
  ID_TURNO: "idTurno",
  NOMBRE: "nombre",
  FECHA_CREACION: "fechaCreacion",
  FECHA_MODIFICACION: "fechaModificacion",
  ACTIVO: "activo",
};

export const CAMPOS_UBICACION = {
  ID_UBICACION: "idUbicacion",
  DESCRIPCION: "descripcion",
  FECHA_CREACION: "fechaCreacion",
  FECHA_MODIFICACION: "fechaModificacion",
  ACTIVO: "activo",
};

export const CAMPOS_USO_INMUEBLE = {
  ID_USO_INMUEBLE: "idUsoInmueble",
  NOMBRE: "nombre",
  FECHA_CREACION: "fechaCreacion",
  FECHA_MODIFICACION: "fechaModificacion",
  ACTIVO: "activo",
};

export const CAMPOS_VERSION_VEHICULAR = {
  ID_VERSION_VEHICULAR: "idVersionVehicular",
  NOMBRE: "nombre",
  DESCRIPCION: "descripcion",
  FECHA_CREACION: "fechaCreacion",
  FECHA_MODIFICACION: "fechaModificacion",
  ACTIVO: "activo",
};

export const CAMPOS_FILTRO_ADMINISTRADOR_SOLICITUDES = {
  PERIODO: "periodo",
  BUSQUEDA_FECHA: "busquedaFecha",
  FECHA_INICIO: "fechaInicio",
  FECHA_FIN: "fechaFin",
  UNIDAD_ADMINISTRATIVA: "unidadAdministrativa",
};

export const CAMPOS_SOLICITUD_MUEBLE = {
  ID_SOLICITUD_MUEBLE: "idSolicitudMueble",
  SOLICITANTE: "solicitante",
  UNIDAD_ADMINISTRATIVA: "unidadAdministrativa",
  OBSERVACIONES: "observaciones",
  TIPO_TRAMITE: "tipoTramite",
  MOTIVO_TRAMITE: "motivoTramite",
  FECHA_CREACION: "fechaCreacion",
  FECHA_MODIFICACION: "fechaModificacion",
};

export const CAMPOS_SOLICITUD_INMUEBLE = {
  ID_SOLICITUD_MUEBLE: "idSolicitudMueble",
  SOLICITANTE: "solicitante",
  UNIDAD_ADMINISTRATIVA: "unidadAdministrativa",
  OBSERVACIONES: "observaciones",
  DOCUMENTO: "documentoReferencia",
  TIPO_TRAMITE: "tipoTramite",
  MOTIVO_TRAMITE: "motivoTramite",
  FECHA_CREACION: "fechaCreacion",
  FECHA_MODIFICACION: "fechaModificacion",
};

export const CAMPOS_SOLICITUD_VEHICULO = {
  ID_SOLICITUD_MUEBLE: "idSolicitudMueble",
  SOLICITANTE: "solicitante",
  UNIDAD_ADMINISTRATIVA: "unidadAdministrativa",
  OBSERVACIONES: "observaciones",
  TIPO_TRAMITE: "tipoTramite",
  MOTIVO_TRAMITE: "motivoTramite",
  FECHA_CREACION: "fechaCreacion",
  FECHA_MODIFICACION: "fechaModificacion",
};

export const CAMPOS_ALTA_MUEBLE = {
  SOLICITUD: "idSolicitud",
  NUMERO_BIENES: "numeroBienes",
  TIPO_BIEN: "tipoBien",
  FAMILIA: "familia",
  SUBFAMILIA: "subfamilia",
  BMS: "bms",
  PARTIDA: "partida",
  PARTIDA_ESPECIFICA: "partidaEspecifica",
  CUENTA_ACTIVO: "cuentaActivo",
  CUENTA_ACTUALIZACION: "cuentaActualizacion",
  DESCRIPCION: "descripcion",
  UNIDAD_ADMINISTRATIVA: "unidadAdministrativa",
  REQUISICION: "requisicion",
  ORDEN_COMPRA: "ordenCompra",
  TIPO_ADQUISICION: "tipoAdquisicion",
  NO_SERIES: "noSeries",
  FOLIO_ANTERIOR: "folioAnterior",
  NO_LICITACION: "noLicitacion",
  FECHA_LICITACION: "fechaLicitacion",
  OBSERVACION_LICITACION: "observacionLicitacion",
  ESTADO_FISICO: "estadoFisico",
  MARCA: "marca",
  COLOR: "color",
  FOLIO_FACTURA: "folioFactura",
  FECHA_FACTURA: "fechaFactura",
  PRECIO_UNITARIO: "precioUnitario",
  FECHA_COMPRA: "fechaCompra",
  DIAS_GARANTIA: "diasGarantia",
  VIDA_UTIL: "vidaUtil",
  FECHA_INICIO_USO: "fechaInicioUso",
  PRECIO_DESECHABLE: "precioDesechable",
  OBSERVACION_BIEN: "observacionBien",
  UBICACION: "ubicacion",
  MUNICIPIO: "municipio",
  AUX_CARACTERISTICA: "auxCaracteristica",
  CARACTERISTICAS: "caracteristicas",
  RESPONSABLES: "responsables",
  OBSERVACION_RESPONSABLE: "observacionResponsable",
};

export const CAMPOS_ALTA_VEHICULO = {
  SOLICITUD: "idSolicitud",
  TIPO_BIEN: "tipoBien",
  FAMILIA: "familia",
  SUBFAMILIA: "subfamilia",
  BMS: "bms",
  PARTIDA: "partida",
  PARTIDA_ESPECIFICA: "partidaEspecifica",
  CUENTA_ACTIVO: "cuentaActivo",
  CUENTA_ACTUALIZACION: "cuentaActualizacion",
  DESCRIPCION: "descripcion",
  UNIDAD_ADMINISTRATIVA: "unidadAdministrativa",
  REQUISICION: "requisicion",
  ORDEN_COMPRA: "ordenCompra",
  TIPO_ADQUISICION: "tipoAdquisicion",
  NO_SERIES: "noSeries",
  FOLIO_ANTERIOR: "folioAnterior",
  NO_LICITACION: "noLicitacion",
  FECHA_LICITACION: "fechaLicitacion",
  OBSERVACION_LICITACION: "observacionLicitacion",
  ESTADO_FISICO: "estadoFisico",
  MARCA: "marca",
  COLOR: "color",
  FOLIO_FACTURA: "folioFactura",
  FECHA_FACTURA: "fechaFactura",
  PRECIO_UNITARIO: "precioUnitario",
  FECHA_COMPRA: "fechaCompra",
  DIAS_GARANTIA: "diasGarantia",
  VIDA_UTIL: "vidaUtil",
  FECHA_INICIO_USO: "fechaInicioUso",
  PRECIO_DESECHABLE: "precioDesechable",
  OBSERVACION_BIEN: "observacionBien",
  UBICACION: "ubicacion",
  MUNICIPIO: "municipio",
  AUX_CARACTERISTICA: "auxCaracteristica",
  CARACTERISTICAS: "caracteristicas",
  RESPONSABLES: "responsables",
  OBSERVACION_RESPONSABLE: "observacionResponsable",

  // Nuevas propiedades
  CUENTA_POR_PAGAR: "cuentaPorPagar",
  SUSTITUYE_BV: "sustituyeBV",
  ANIO_EMICION: "anioEmicion",
  NUMERO_PLACA: "numeroPlacaVehiculo",
  NUMERO_MOTOR: "numeroMotor",
  ANIO_MODELO: "anioModelo",
  NUMERO_ECONOMICO: "numeroEconomico",
  ID_CLAVE: "idClave",
  ID_LINEA: "idLinea",
  ID_VERSION: "idVersion",
  ID_CLASE: "idClase",
  ID_TIPO: "idTipo",
  ID_COMBUSTIBLE: "idCombustible",
};

export const CAMPOS_ALTA_INMUEBLE = {
  ID_SOLICITUD: "idSolicitud",
  REFERENCIA_CONAC: "referenciaConac",
  ID_FAMILIA: "idFamilia",
  ID_SUBFAMILIA: "idSubfamilia",
  NOMENCLATURA: "nomenclatura",
  DESCRIPCION: "descripcion",
  ID_TIPO_INMUEBLE: "idTipoInmueble",
  ID_USO_INMUEBLE: "idUsoInmueble",
  ID_TIPO_DOMINIO: "idTipoDominio",
  ID_ESTADO_FISICO: "idEstadoFisico",
  ID_TIPO_AFECTACION: "idTipoAfectacion",
  AFECTANTE: "afectante",
  ID_TIPO_ADQUISICION: "idTipoAdquisicion",
  DECRETO_PUBLICACION: "decretoPublicaicion",
  ESCRITURA_TITULO: "escrituraTitulo",
  FECHA_ADQUISICION: "fechaAdquisicion",
  FECHA_ALTA_SISTEMA: "fechaAltaSistema",
  EXPEDIENTE: "expediente",
  VALOR_HISTORICO: "valorHistorico",
  VALOR_LIBROS: "valorLibros",
  DEPRECIACION: "depreciacion",
  ANIOS_VIDA_UTIL: "aniosVidaUtil",
  FOLIO_CATASTRO: "folioCatastro",
  CALLE: "calle",
  SUPERFICIE: "superficie",
  VALOR_TERRENO: "valorTerreno",
  NUMERO_EXTERIOR: "numeroExterior",
  NUMERO_INTERIOR: "numeroInterior",
  CRUZAMIENTO_1: "cruzamimiento1",
  CRUZAMIENTO_2: "cruzamimiento2",
  SUPERFICIE_CONSTRUCCION: "superficieConstruccion",
  TABLAJE: "tablaje",
  VALOR_CONSTRUCCION: "valorConstruccion",
  VALOR_INICIAL: "valorInicial",
  CODIGO_POSTAL: "codigoPostal",
  ID_ORIGEN_VALOR: "idOrigenValor",
  MUNICIPIO: "municipio",
  ASENTAMIENTO: "asentamiento",
  PROPIETARIO: "propietario",
  SECRETARIA: "secretria",
  DIRECCION: "direccion",
  DEPARTAMENTO: "departamento",
  OBSERVACION_INMUEBLE: "observacionInmueble",
  OBSERVACION_SUPERVISION: "observacionSupervicion",
};

export const CAMPOS_MODIFICACION_INMUEBLE = {
  ID_SOLICITUD: "idSolicitud",
  BIEN: "bien",
  REFERENCIA_CONAC: "referenciaConac",
  ID_FAMILIA: "idFamilia",
  ID_SUBFAMILIA: "idSubfamilia",
  NOMENCLATURA: "nomenclatura",
  DESCRIPCION: "descripcion",
  ID_TIPO_INMUEBLE: "idTipoInmueble",
  ID_USO_INMUEBLE: "idUsoInmueble",
  ID_TIPO_DOMINIO: "idTipoDominio",
  ID_ESTADO_FISICO: "idEstadoFisico",
  ID_TIPO_AFECTACION: "idTipoAfectacion",
  AFECTANTE: "afectante",
  ID_TIPO_ADQUISICION: "idTipoAdquisicion",
  DECRETO_PUBLICACION: "decretoPublicaicion",
  ESCRITURA_TITULO: "escrituraTitulo",
  FECHA_ADQUISICION: "fechaAdquisicion",
  FECHA_ALTA_SISTEMA: "fechaAltaSistema",
  EXPEDIENTE: "expediente",
  VALOR_HISTORICO: "valorHistorico",
  VALOR_LIBROS: "valorLibros",
  DEPRECIACION: "depreciacion",
  ANIOS_VIDA_UTIL: "aniosVidaUtil",
  FOLIO_CATASTRO: "folioCatastro",
  CALLE: "calle",
  SUPERFICIE: "superficie",
  VALOR_TERRENO: "valorTerreno",
  NUMERO_EXTERIOR: "numeroExterior",
  NUMERO_INTERIOR: "numeroInterior",
  CRUZAMIENTO_1: "cruzamimiento1",
  CRUZAMIENTO_2: "cruzamimiento2",
  SUPERFICIE_CONSTRUCCION: "superficieConstruccion",
  TABLAJE: "tablaje",
  VALOR_CONSTRUCCION: "valorConstruccion",
  VALOR_INICIAL: "valorInicial",
  CODIGO_POSTAL: "codigoPostal",
  ID_ORIGEN_VALOR: "idOrigenValor",
  MUNICIPIO: "municipio",
  ASENTAMIENTO: "asentamiento",
  PROPIETARIO: "propietario",
  SECRETARIA: "secretria",
  DIRECCION: "direccion",
  DEPARTAMENTO: "departamento",
  OBSERVACION_INMUEBLE: "observacionInmueble",
  OBSERVACION_SUPERVISION: "observacionSupervicion",
};

export const CAMPOS_MODIFICACION_MUEBLE = {
  SOLICITUD: "idSolicitud",
  BIEN: "bien",
  FOLIO_BIEN: "folioBien",
  TIPO_BIEN: "tipoBien",
  FAMILIA: "familia",
  SUBFAMILIA: "subfamilia",
  BMS: "bms",
  DESCRIPCION: "descripcion",
  PARTIDA: "partida",
  PARTIDA_ESPECIFICA: "partidaEspecifica",
  CUENTA_ACTIVO: "cuentaActivo",
  CUENTA_ACTUALIZACION: "cuentaActualizacion",
  UNIDAD_ADMINISTRATIVA: "unidadAdministrativa",
  CENTRO_COSTO: "centroCosto",
  REQUISICION: "requisicion",
  ORDEN_COMPRA: "ordenCompra",
  TIPO_ADQUISICION: "tipoAdquisicion",
  NO_SERIES: "noSeries",
  FOLIO_ANTERIOR: "folioAnterior",
  NO_LICITACION: "noLicitacion",
  FECHA_LICITACION: "fechaLicitacion",
  OBSERVACION_LICITACION: "observacionLicitacion",
  ESTADO_FISICO: "estadoFisico",
  MARCA: "marca",
  COLOR: "color",
  FOLIO_FACTURA: "folioFactura",
  FECHA_FACTURA: "fechaFactura",
  PRECIO_UNITARIO: "precioUnitario",
  FECHA_COMPRA: "fechaCompra",
  DIAS_GARANTIA: "diasGarantia",
  VIDA_UTIL: "vidaUtil",
  FECHA_INICIO_USO: "fechaInicioUso",
  PRECIO_DESECHABLE: "precioDesechable",
  OBSERVACION_BIEN: "observacionBien",
  UBICACION: "ubicacion",
  MUNICIPIO: "municipio",
  AUX_CARACTERISTICA: "auxCaracteristica",
  CARACTERISTICAS: "caracteristicas",
  RESPONSABLES: "responsables",
  OBSERVACION_RESPONSABLE: "observacionResponsable",
  MOTIVO_TRAMITE: "motivoTramite",
};

export const CAMPOS_MODIFICACION_VEHICULO = {
  SOLICITUD: "idSolicitud",
  BIEN: "bien",
  FOLIO_BIEN: "folioBien",
  TIPO_BIEN: "tipoBien",
  FAMILIA: "familia",
  SUBFAMILIA: "subfamilia",
  BMS: "bms",
  PARTIDA: "partida",
  PARTIDA_ESPECIFICA: "partidaEspecifica",
  CUENTA_ACTIVO: "cuentaActivo",
  CUENTA_ACTUALIZACION: "cuentaActualizacion",
  DESCRIPCION: "descripcion",
  UNIDAD_ADMINISTRATIVA: "unidadAdministrativa",
  CENTRO_COSTO: "centroCosto",
  REQUISICION: "requisicion",
  ORDEN_COMPRA: "ordenCompra",
  TIPO_ADQUISICION: "tipoAdquisicion",
  NO_SERIES: "noSeries",
  FOLIO_ANTERIOR: "folioAnterior",
  NO_LICITACION: "noLicitacion",
  FECHA_LICITACION: "fechaLicitacion",
  OBSERVACION_LICITACION: "observacionLicitacion",
  ESTADO_FISICO: "estadoFisico",
  MARCA: "marca",
  COLOR: "color",
  FOLIO_FACTURA: "folioFactura",
  FECHA_FACTURA: "fechaFactura",
  PRECIO_UNITARIO: "precioUnitario",
  FECHA_COMPRA: "fechaCompra",
  DIAS_GARANTIA: "diasGarantia",
  VIDA_UTIL: "vidaUtil",
  FECHA_INICIO_USO: "fechaInicioUso",
  PRECIO_DESECHABLE: "precioDesechable",
  OBSERVACION_BIEN: "observacionBien",
  UBICACION: "ubicacion",
  MUNICIPIO: "municipio",
  AUX_CARACTERISTICA: "auxCaracteristica",
  CARACTERISTICAS: "caracteristicas",
  RESPONSABLES: "responsables",
  OBSERVACION_RESPONSABLE: "observacionResponsable",

  // Nuevas propiedades
  CUENTA_POR_PAGAR: "cuentaPorPagar",
  SUSTITUYE_BV: "sustituyeBV",
  ANIO_EMICION: "anioEmicion",
  NUMERO_PLACA: "numeroPlacaVehiculo",
  NUMERO_MOTOR: "numeroMotor",
  ANIO_MODELO: "anioModelo",
  NUMERO_ECONOMICO: "numeroEconomico",
  ID_CLAVE: "idClave",
  ID_LINEA: "idLinea",
  ID_VERSION: "idVersion",
  ID_CLASE: "idClase",
  ID_TIPO: "idTipo",
  ID_COMBUSTIBLE: "idCombustible",
  MOTIVO_TRAMITE: "motivoTramite",
};

export const CAMPOS_BAJA_MUEBLE = {
  FOLIO_SOLICITUD: "folioSolicitud",
  UNIDAD_ADMINISTRATIVA: "unidadAdministrativa",
  TIPO_BIEN: "tipoBien",
  FOLIO_BIEN: "folioBien",
  AUX_FOLIO_BIEN: "auxFolioBien",
  OBSERVACIONES: "observaciones",
  FOLIO_DOCUMENTO: "folioDocumento",
  FECHA_DOCUMENTO: "fechaDocumento",
  LISTA_DOCUMENTO: "listaDocumentos",
  NOMBRE_SOLICITANTE: "nombreSolicitante",
  LUGAR_RESGUARDO: "lugarResguardo",
};

export const CAMPOS_BAJA_VEHICULO = {
  FOLIO_SOLICITUD: "folioSolicitud",
  UNIDAD_ADMINISTRATIVA: "unidadAdministrativa",
  EMPLEADO: "empleado",
  TIPO_BIEN: "tipoBien",
  FOLIO_BIEN: "folioBien",
  AUX_FOLIO_BIEN: "auxFolioBien",
  OBSERVACIONES: "observaciones",
  FOLIO_DOCUMENTO: "folioDocumento",
  FECHA_DOCUMENTO: "fechaDocumento",
  LISTA_DOCUMENTO: "listaDocumentos",
};

export const CAMPOS_BAJA_INMUEBLE = {
  ID_SOLICITUD: "idSolicitud",
  FOLIO_BIEN: "folioBien",
  ID_BIEN_PATRIMONIO: "idBienPatrimonio",
  FECHA_DESINCORPORACION: "fechaDesincorporacion",
  FECHA_BAJA: "fechaBaja",
  FECHA_BAJA_SISTEMA: "fechaBajaSistema",
  VALOR_BAJA: "valorBaja",
  A_FAVOR: "aFavor",
  DESTINO_BIEN: "destinoBien",
  ESCRITURA_TITULO: "escrituraTitulo",
  JUSTIFICACION_BAJA: "justificacionBaja",
};

export const CAMPOS_MOVIMIENTO_MUEBLE = {
  FOLIO_SOLICITUD: "folioSolicitud",
  UNIDAD_ADMINISTRATIVA: "unidadAdministrativa",
  TIPO_BIEN: "tipoBien",
  FOLIO_BIEN: "folioBien",
  NUEVO_CENTRO_COSTO: "centroCosto",
  UBICACION: "ubicacion",
  MUNICIPIO: "municipio",
  NUEVO_RESGUARDANTE: "resguardantes",
  MOTIVO_TRAMITE: "motivoTramite",
};

export const CAMPOS_MOVIMIENTO_VEHICULO = {
  FOLIO_SOLICITUD: "folioSolicitud",
  UNIDAD_ADMINISTRATIVA: "unidadAdministrativa",
  TIPO_BIEN: "tipoBien",
  FOLIO_BIEN: "folioBien",
  NUEVO_CENTRO_COSTO: "centroCosto",
  UBICACION: "ubicacion",
  MUNICIPIO: "municipio",
  NUEVO_RESGUARDANTE: "resguardantes",
  MOTIVO_TRAMITE: "motivoTramite",
};

export const CAMPOS_DESINCORPORACION_MUEBLE = {
  FOLIO_SOLICITUD: "folioSolicitud",
  UNIDAD_ADMINISTRATIVA: "unidadAdministrativa",
  TIPO_BIEN: "tipoBien",
  FOLIO_BIEN: "folioBien",
  OBSERVACIONES: "observaciones",
  FECHA_PUBLICACION: "fechaPublicacion",
  NO_PUBLICACION: "noPublicacion",
  DESCRIPCION_DESINCORPORACION: "descripcion",
};

export const CAMPOS_DESINCORPORACION_VEHICULO = {
  FOLIO_SOLICITUD: "folioSolicitud",
  EMPLEADO: "empleado",
  UNIDAD_ADMINISTRATIVA: "unidadAdministrativa",
  TIPO_BIEN: "tipoBien",
  FOLIO_BIEN: "folioBien",
  OBSERVACIONES: "observaciones",
  FECHA_PUBLICACION: "fechaPublicacion",
  NO_PUBLICACION: "noPublicacion",
  DESCRIPCION_DESINCORPORACION: "descripcion",
};

export const CAMPOS_DESTINO_FINAL_MUEBLE = {
  FOLIO_SOLICITUD: "folioSolicitud",
  UNIDAD_ADMINISTRATIVA: "unidadAdministrativa",
  TIPO_BIEN: "tipoBien",
  FOLIO_BIEN: "folioBien",
  FOLIO_ENAJENACION: "folioEnajenacion",
  FECHA_ENAJENACION: "fechaEnajenacion",
  AVALUO_ENAJENACION: "avaluoEnajenacion",
  IMPORTE_ENAJENACION: "importeEnajenacion",
  DESCRIPCION_ENAJENACION: "descripcion",
  FOLIO_DESTRUCCION: "folioDestruccion",
  FECHA_DESTRUCCION: "fechaDestruccion",
  DESCRIPCION_DESTRUCCION: "descripcion",
  MOTIVO_TRAMITE: "motivoTramite",
};

export const CAMPOS_DESTINO_FINAL_VEHICULO = {
  FOLIO_SOLICITUD: "folioSolicitud",
  EMPLEADO: "empleado",
  UNIDAD_ADMINISTRATIVA: "unidadAdministrativa",
  TIPO_BIEN: "tipoBien",
  FOLIO_BIEN: "folioBien",
  FOLIO_ENAJENACION: "folioEnajenacion",
  FECHA_ENAJENACION: "fechaEnajenacion",
  AVALUO_ENAJENACION: "avaluoEnajenacion",
  IMPORTE_ENAJENACION: "importeEnajenacion",
  DESCRIPCION_ENAJENACION: "descripcion",
  FOLIO_DESTRUCCION: "folioDestruccion",
  FECHA_DESTRUCCION: "fechaDestruccion",
  DESCRIPCION_DESTRUCCION: "descripcion",
  MOTIVO_TRAMITE: "motivoTramite",
};

export const CAMPOS_FILTRO_INVENTARIO = {
  PERIODO: "periodo",
  UNIDAD_ADMINISTRATIVA: "unidadAdministrativa",
  TIPO_BIEN: "tipoBien",
  ESTADO_BIEN: "estadoBien",
  BUSQUEDA_FECHA: "busquedaFecha",
  FECHA_INICIO: "fechaInicio",
  FECHA_FIN: "fechaFin",

  MONTO_TOTAL_DEPRECIADO: "montoTotal",
  MONTO_FALTANTE: "montoFaltante",
  VALOR_HISTORICO: "valorHistorico",
  ANIOS_VIDA: "aniosVida",
  DEPRECIACION_ANUAL: "depreciacionAnual",
  DEPRECIACION_MENSUAL: "depreciacionMensual",
};

export const CAMPOS_INVENTARIO_MUEBLE = {
  BIEN: "idBien",
  FOLIO_BIEN: "folioBien",
  FECHA_ALTA: "fechaAlta",
  FECHA_BAJA: "fechaBaja",
  MOTIVO_BAJA: "motivoBaja",
  TIPO_BIEN: "tipoBien",
  FAMILIA: "familia",
  SUBFAMILIA: "subfamilia",
  BMS: "bms",
  PARTIDA: "partida",
  PARTIDA_ESPECIFICA: "partidaEspecifica",
  CUENTA_ACTIVO: "cuentaActivo",
  CUENTA_ACTUALIZACION: "cuentaActualizacion",
  DESCRIPCION: "descripcion",
  UNIDAD_ADMINISTRATIVA: "unidadAdministrativa",
  REQUISICION: "requisicion",
  ORDEN_COMPRA: "ordenCompra",
  TIPO_ADQUISICION: "tipoAdquisicion",
  NO_SERIES: "noSeries",
  FOLIO_ANTERIOR: "folioAnterior",
  NO_LICITACION: "noLicitacion",
  FECHA_LICITACION: "fechaLicitacion",
  OBSERVACION_LICITACION: "observacionLicitacion",
  ESTADO_FISICO: "estadoFisico",
  MARCA: "marca",
  COLOR: "color",
  FOLIO_FACTURA: "folioFactura",
  FECHA_FACTURA: "fechaFactura",
  PRECIO_UNITARIO: "precioUnitario",
  FECHA_COMPRA: "fechaCompra",
  DIAS_GARANTIA: "diasGarantia",
  VIDA_UTIL: "vidaUtil",
  FECHA_INICIO_USO: "fechaInicioUso",
  PRECIO_DESECHABLE: "precioDesechable",
  OBSERVACION_BIEN: "observacionBien",
  UBICACION: "ubicacion",
  MUNICIPIO: "municipio",
  AUX_CARACTERISTICA: "auxCaracteristica",
  CARACTERISTICAS: "caracteristicas",
  RESPONSABLES: "responsables",
  OBSERVACION_RESPONSABLE: "observacionResponsable",
};

export const CAMPOS_INVENTARIO_VEHICULO = {
  BIEN: "idBien",
  FOLIO_BIEN: "folioBien",
  FECHA_ALTA: "fechaAlta",
  FECHA_BAJA: "fechaBaja",
  MOTIVO_BAJA: "motivoBaja",
  TIPO_BIEN: "tipoBien",
  FAMILIA: "familia",
  SUBFAMILIA: "subfamilia",
  BMS: "bms",
  PARTIDA: "partida",
  PARTIDA_ESPECIFICA: "partidaEspecifica",
  CUENTA_ACTIVO: "cuentaActivo",
  CUENTA_ACTUALIZACION: "cuentaActualizacion",
  DESCRIPCION: "descripcion",
  UNIDAD_ADMINISTRATIVA: "unidadAdministrativa",
  REQUISICION: "requisicion",
  ORDEN_COMPRA: "ordenCompra",
  TIPO_ADQUISICION: "tipoAdquisicion",
  NO_SERIES: "noSeries",
  FOLIO_ANTERIOR: "folioAnterior",
  NO_LICITACION: "noLicitacion",
  FECHA_LICITACION: "fechaLicitacion",
  OBSERVACION_LICITACION: "observacionLicitacion",
  ESTADO_FISICO: "estadoFisico",
  MARCA: "marca",
  COLOR: "color",
  FOLIO_FACTURA: "folioFactura",
  FECHA_FACTURA: "fechaFactura",
  PRECIO_UNITARIO: "precioUnitario",
  FECHA_COMPRA: "fechaCompra",
  DIAS_GARANTIA: "diasGarantia",
  VIDA_UTIL: "vidaUtil",
  FECHA_INICIO_USO: "fechaInicioUso",
  PRECIO_DESECHABLE: "precioDesechable",
  OBSERVACION_BIEN: "observacionBien",
  UBICACION: "ubicacion",
  MUNICIPIO: "municipio",
  AUX_CARACTERISTICA: "auxCaracteristica",
  CARACTERISTICAS: "caracteristicas",
  RESPONSABLES: "responsables",
  OBSERVACION_RESPONSABLE: "observacionResponsable",

  // Nuevas propiedades
  CUENTA_POR_PAGAR: "cuentaPorPagar",
  SUSTITUYE_BV: "sustituyeBV",
  ANIO_EMICION: "anioEmicion",
  NUMERO_PLACA: "numeroPlacaVehiculo",
  NUMERO_MOTOR: "numeroMotor",
  ANIO_MODELO: "anioModelo",
  NUMERO_ECONOMICO: "numeroEconomico",
  ID_CLAVE: "idClave",
  ID_LINEA: "idLinea",
  ID_VERSION: "idVersion",
  ID_CLASE: "idClase",
  ID_TIPO: "idTipo",
  ID_COMBUSTIBLE: "idCombustible",
};

export const CAMPOS_INVENTARIO_INMUEBLE = {
  BIEN: "idBien",
  FOLIO_BIEN: "folioBien",
  FECHA_ALTA: "fechaAlta",
  FECHA_BAJA: "fechaBaja",
  MOTIVO_BAJA: "motivoBaja",
  REFERENCIA_CONAC: "referenciaConac",
  ID_FAMILIA: "idFamilia",
  ID_SUBFAMILIA: "idSubfamilia",
  NOMENCLATURA: "nomenclatura",
  DESCRIPCION: "descripcion",
  ID_TIPO_INMUEBLE: "idTipoInmueble",
  ID_USO_INMUEBLE: "idUsoInmueble",
  ID_TIPO_DOMINIO: "idTipoDominio",
  ID_ESTADO_FISICO: "idEstadoFisico",
  ID_TIPO_AFECTACION: "idTipoAfectacion",
  AFECTANTE: "afectante",
  ID_TIPO_ADQUISICION: "idTipoAdquisicion",
  DECRETO_PUBLICACION: "decretoPublicaicion",
  ESCRITURA_TITULO: "escrituraTitulo",
  FECHA_ADQUISICION: "fechaAdquisicion",
  FECHA_ALTA_SISTEMA: "fechaAltaSistema",
  EXPEDIENTE: "expediente",
  VALOR_HISTORICO: "valorHistorico",
  VALOR_LIBROS: "valorLibros",
  DEPRECIACION: "depreciacion",
  ANIOS_VIDA_UTIL: "aniosVidaUtil",
  FOLIO_CATASTRO: "folioCatastro",
  CALLE: "calle",
  SUPERFICIE: "superficie",
  VALOR_TERRENO: "valorTerreno",
  NUMERO_EXTERIOR: "numeroExterior",
  NUMERO_INTERIOR: "numeroInterior",
  CRUZAMIENTO_1: "cruzamimiento1",
  CRUZAMIENTO_2: "cruzamimiento2",
  SUPERFICIE_CONSTRUCCION: "superficieConstruccion",
  TABLAJE: "tablaje",
  VALOR_CONSTRUCCION: "valorConstruccion",
  VALOR_INICIAL: "valorInicial",
  CODIGO_POSTAL: "codigoPostal",
  ID_ORIGEN_VALOR: "idOrigenValor",
  MUNICIPIO: "municipio",
  ASENTAMIENTO: "asentamiento",
  PROPIETARIO: "propietario",
  SECRETARIA: "secretria",
  DIRECCION: "direccion",
  DEPARTAMENTO: "departamento",
  OBSERVACION_INMUEBLE: "observacionInmueble",
  OBSERVACION_SUPERVISION: "observacionSupervicion",
};

export const CAMPOS_DEPRECIACION = {
  PERIODO: "periodo",
  UNIDAD_ADMINISTRATIVA: "unidadAdministrativa",
  TIPO_BIEN: "tipoBien",
  MES: "estadoBien",
  TIPO_DEPRECIACION: "busquedaFecha",
  FOLIO_BMS: "fechaInicio",
  FECHA_FIN: "fechaFin",

  MONTO_TOTAL_DEPRECIADO: "montoTotal",
  NUMERO_BIENES_DEPRECIADOS: "numeroBienesDepre",
  NUMERO_BIENES_NO_DEPRECIADOS: "numeroBienesNoDepre",
  TOTAL_BIENES: "totalBienes",
};

export const CAMPOS_ALMACEN = {
  ID_ALMACEN: "idAlmacen",
  ID_PERIODO: "idPeriodo",
  NOMBRE: "nombre",
  DIRECCION: "direccion",
  HORARIO: "horario",
  ID_EMPLEADO: "idEmpleado",
  ID_CUENTA: "idCuenta",
  ID_METODO_COSTEO: "idMetodoCosteo",
  FOLIO_ENTRADA: "folioEntrada",
  FOLIO_SALIDA: "folioSalida",
  FECHA_CREACION: "fechaCreacion",
  FECHA_MODIFICACION: "fechaModificacion",
  ACTIVO: "activo",
};

export const CAMPOS_CONCEPTO_MOVIMIENTO = {
  ID_CONCEPTO_MOVIMIENTO: "idConceptoMovimiento",
  NOMBRE: "nombre",
  DESCRIPCION: "descripcion",
  ID_TIPO_MOVIMIENTO: "idTipoMovimiento",
  FECHA_CREACION: "fechaCreacion",
  FECHA_MODIFICACION: "fechaModificacion",
  ACTIVO: "activo",
};

export const CAMPOS_METODO_ADQUISICION = {
  ID_METODO_ADQUISICION: "idMetodoAdquisicion",
  NOMBRE: "nombre",
  FECHA_CREACION: "fechaCreacion",
  FECHA_MODIFICACION: "fechaModificacion",
  ACTIVO: "activo",
};

export const CAMPOS_FILTRO_ENTRADA_SALIDA = {
  PERIODO: "periodo",
  BUSQUEDA_FECHA: "busquedaFecha",
  FECHA_INICIO: "fechaInicio",
  FECHA_FIN: "fechaFin",
};

export const CAMPOS_MOVIMIENTO = {
  FOLIO_MOVIMIENTO: "folioMovimiento",
  ID_TIPO_MOVIMIENTO: "idTipoMovimiento",
  ID_ALMACEN: "idAlmacen",
  ID_METODO_ADQUISICION: "idMetodoAdquisicion",
  ID_PROGRAMA_OPERATIVO: "idProgramaOperativo",
  NUMERO_FACTURA: "numeroFactura",
  FECHA_RECEPCION: "fechaResepcion",
  ID_FUENTE_FINANCIAMIENTO: "idFuenteFinanciamiento",
  ID_CONCEPTO_MOVIMIENTO: "idConceptoMovimiento",
  ID_PROVEEDOR: "idProveedor",
  ID_FAMILIA: "idFamilia",
  OBSERVACIONES: "observaciones",
  IMPORTE_TOTAL: "importeTotal",
  ARTICULOS: "articulos",
  AUX_ARTICULOS: "articulosaux",
};

export const CAMPOS_INVENTARIO_ALMACEN = {
  FOLIO_BIEN: "folioBien",
  PERIODO: "periodo",
  ID_ALMACEN: "idAlmacen",
  ID_BMS: "bms",
  ID_FAMILIA: "idFamilia",
  CODIGO_ARMONIZADO: "codigoArmonizado",
  EXISTENCIA: "existencia",
  PRECIO_UNITARIO: "precioUnitario",
  FECHA_CREACION: "fechaCreacion",
  FECHA_MODIFICACION: "fechaModificacion",
  UNIDAD_MEDIDA: "unidadMedida",
};
