import { ROUTES } from "./routeConfig";

export const CLAVE_TOKEN = "auth_token";

export const IDS_SECCIONES = {
  MENU_PRINCIPAL: 1,
  CATALOGOS: 2,
};

export const IDS_MODULOS = {
  SEGURIDAD: 1,
  PATRIMONIO: 2,
  ALMACEN: 3,
};

export const IDS_SUBMODULOS = {
  INCIO: -1,
  MENU: 0,
  ADMINISTRADOR_CEDULAS_BIENES_MUEBLES: 1,
  ADMINISTRADOR_CEDULAS_BIENES_INMUEBLES: 2,
  ADMINISTRADOR_CEDULAS_BIENES_VEHICULARES: 3,
  INVENTARIO_BIENES_MUEBLES: 4,
  INVENTARIO_BIENES_INMUEBLES: 5,
  INVENTARIO_BIENES_VEHICULARES: 6,
  ADMINISTRADOR_CATALOGOS_SIP: 7,
  DEPRECIACION: 8,
  ENTRADAS_SALIDAS: 9,
  INVENTARIO_ALMACENES: 10,
  ADMINISTRADOR_CATALOGOS_SIA: 11,
  ADMINISTRADOR_EMPLEADOS_USUARIOS: 13,
  PERFIL: 14,
};

export const TIPOS_TRAMITES = {
  ALTA_MUEBLE: 1,
  BAJA_MUEBLE: 2,
  MODIFICACION_MUEBLE: 3,
  MOVIMIENTO_MUEBLE: 4,
  DESINCORPORACION_MUEBLE: 5,
  DESTINO_FINAL_MUEBLE: 6,
  ALTA_VEHICULAR: 7,
  BAJA_VEHICULAR: 8,
  ACTUALIZACION_VEHICULAR: 9,
  MOVIMIENTO_VEHICULAR: 10,
  DESINCORPORACION_VEHICULAR: 11,
  DESTINO_FINAL_VEHICULAR: 12,
  ALTA_INMUEBLE: 13,
  BAJA_INMUEBLE: 14,
  MODIFICACION_INMUEBLE: 15,
};

export const MOTIVO_TRAMITE = {
  ALTA_DE_BIENES_EN_COMPENSACION: 1,
  ALTA_DE_MOBILIARIO_POR_CARGA_DESDE_EL_SISTEMA_DE_EGRESOS: 2,
  ALTA_POR_ADJUDICACION_POR_EMBARGO: 3,
  ALTA_POR_ADQUISICION_DE_MUEBLES_ANIOS_ANTERIORES: 4,
  ALTA_POR_ADQUISICION_DIRECTA_DE_BIENES_MUEBLES: 5,
  ALTA_POR_ADQUISICION_DIRECTA_DE_BIENES_MUEBLES_CON_RECURSOS_FEDERALES: 6,
  ALTA_POR_DIFERENCIA_DE_INVENTARIOS: 7,
  ALTA_POR_DIFERENCIA_ENTREGA_RECEPCION: 8,
  ALTA_POR_DONACION_DE_BIENES_MUEBLES: 9,
  ALTA_POR_EXTINCION: 10,
  ALTA_POR_LICITACION: 11,
  BAJA_DE_MOBILIARIO_POR_EXTRAVIO: 12,
  BAJA_DE_MOBILIARIO_POR_ROBO: 13,
  BAJA_DE_MOBILIARIO_POR_SINIESTRO: 14,
  BAJA_DE_MOBILIARIO_POR_INSERVIBLE: 15,
  BAJA_DE_MOBILIARIO_TOTAL: 16,
  BAJA_DE_MOBILIARIO_POR_DONACION: 17,
  BAJA_DE_MOBILIARIO_POR_DUPLICIDAD: 18,
  BAJA_DE_MOBILIARIO_EN_ARRENDAMIENTO: 19,
  BAJA_DE_MOBILIARIO_POR_TERMINO_DE_CONTRATO: 20,
  MODIFICACION_DE_DATOS_DE_FACTURA: 21,
  MODIFICACION_DE_DATOS_DE_MOBILIARIO_Y_EQUIPO: 22,
  ACTUALIZACION_DE_DATOS_DE_BIENES_MUEBLES_INCORPORADOS_DEL_SISTEMA_DE_COMPRAS: 23,
  CAMBIO_DE_CENTRO_DE_COSTOS: 24,
  CAMBIO_DE_RESGUARDOS_DE_MOBILIARIO_Y_EQUIPO: 25,
  TRANSFERENCIA_DE_BIENES_MUEBLES: 26,
  DESINCORPORACION_DE_BIENES_MUEBLES: 27,
  DESTRUCCION: 28,
  ENAJENACION: 29,
  ALTA_POR_LICITACION_EN_OFICIALIA_DE_MAQUINARIAS_Y_VEHICULOS: 30,
  ALTA_POR_LICITACION_EN_LAS_DEPENDENCIAS_DE_MAQUINARIA_Y_VEHICULOS: 31,
  ALTA_POR_DONACION_DE_MAQUINARIA_Y_VEHICULOS: 32,
  ALTA_POR_ADQUISICION_DIRECTA_DE_MAQUINARIA_Y_VEHICULOS: 33,
  ALTA_POR_ADQUISICION_DIRECTA_DE_MAQUINARIA_Y_VEHICULOS_CON_RECURSOS_FEDERALES: 34,
  ALTA_POR_ADQUISICION_DE_VEHICULOS_ANIOS_ANTERIORES: 35,
  ALTA_POR_ADJUDICACION_POR_EMBARGO_DE_MAQUINARIA_Y_VEHICULOS: 36,
  ALTA_DE_VEHICULOS_POR_EXTINCION: 37,
  ALTA_DE_VEHICULOS_EN_COMPENSACION: 38,
  BAJA_DE_VEHICULOS_POR_ROBO: 39,
  BAJA_DE_VEHICULOS_POR_SINIESTRO: 40,
  BAJA_DE_VEHICULOS_POR_EXTRAVIO: 41,
  BAJA_DE_VEHICULOS_POR_DUPLICIDAD: 42,
  BAJA_DE_VEHICULOS_POR_INSERVIBLE: 43,
  BAJA_DE_VEHICULOS_TOTAL: 44,
  BAJA_DE_VEHICULOS_POR_DONACION: 45,
  BAJA_DE_VEHICULOS_POR_MOTIVOS_EXTRAORDINARIOS: 46,
  ACTUALIZACION_DE_DATOS_DE_BIENES_VEHICULOS: 47,
  ACTUALIZACION_DE_DATOS_DE_LA_FACTURA_DE_BIENES_VEHICULOS: 48,
  ACTUALIZACION_DE_BIENES_VEHICULOS_INCORPORADOS_DEL_SISTEMA_DE_COMPRAS: 49,
  CAMBIO_DE_CENTRO_DE_COSTOS_VEHICULOS: 50,
  TRANSFERENCIAS_VEHICULOS: 51,
  CAMBIO_DE_RESGUARDANTE: 52,
  DESINCORPORACION: 53,
  ENAJENACION_VEHICULOS: 54,
  DESTRUCCION_VEHICULOS: 55,
  ALTA_POR_INSCRIPCION_PRIMITIVA: 56,
  ALTA_POR_DONACION: 57,
  ALTA_POR_COMPRAVENTA: 58,
  ALTA_POR_DIVISION: 59,
  ALTA_POR_PERMUTA: 60,
  ALTA_POR_ADJUDICACION_A_TITULO_GRATUITO: 61,
  ALTA_POR_COMPRAVENTA_JUDICIAL: 62,
  ALTA_POR_EXPROPIACION: 63,
  BAJA_POR_COMPRAVENTA: 64,
  BAJA_POR_DONACION: 65,
  BAJA_POR_UNION: 66,
  BAJA_POR_PERMUTA: 67,
  BAJA_POR_DACION_EN_PAGO: 68,
  BAJA_POR_SENTENCIA_JUDICIAL: 69,
  BAJA_POR_RESOLUCION_ADMINISTRATIVA: 70,
  BAJA_POR_USO_COMUN: 71,
  BAJA_POR_IRREGULARIDAD: 72,
  MODIFICACION_DE_DATOS_DEL_INMUEBLE: 73,
  MODIFICACION_POR_CORRECCION_DE_MEDIDAS: 74,
  MODIFICACION_POR_CONSTRUCCION: 75,
  MODIFICACION_POR_MEJORAS: 76,
  MODIFICACION_POR_AFECTACION: 77,
};

export const navInfoInicioConfig = {
  idSubModulo: IDS_SUBMODULOS.INCIO,
  nombre: "Inicio SICBA",
  abreviacion: "MI",
  modulo: "Módulo de Inicio",
};

export const modulosConfig = new Map([
  [
    IDS_MODULOS.SEGURIDAD,
    {
      path: ROUTES.MENU_SEGURIDAD,
    },
  ],
  [
    IDS_MODULOS.PATRIMONIO,
    {
      path: ROUTES.MENU_PATRIMONIO,
    },
  ],
  [
    IDS_MODULOS.ALMACEN,
    {
      path: ROUTES.MENU_ALMANCEN,
    },
  ],
]);

export const subModulosConfig = new Map([
  [
    IDS_SUBMODULOS.ADMINISTRADOR_CEDULAS_BIENES_MUEBLES,
    {
      path: ROUTES.ADMINISTRADOR_CEDULAS_BIENES_MUEBLES,
    },
  ],
  [
    IDS_SUBMODULOS.ADMINISTRADOR_CEDULAS_BIENES_INMUEBLES,
    {
      path: ROUTES.ADMINISTRADOR_CEDULAS_BIENES_INMUEBLES,
    },
  ],
  [
    IDS_SUBMODULOS.ADMINISTRADOR_CEDULAS_BIENES_VEHICULARES,
    {
      path: ROUTES.ADMINISTRADOR_CEDULAS_BIENES_VEHICULARES,
    },
  ],
  [
    IDS_SUBMODULOS.INVENTARIO_BIENES_MUEBLES,
    {
      path: ROUTES.INVENTARIO_BIENES_MUEBLES,
    },
  ],
  [
    IDS_SUBMODULOS.INVENTARIO_BIENES_INMUEBLES,
    {
      path: ROUTES.INVENTARIO_BIENES_INMUEBLES,
    },
  ],
  [
    IDS_SUBMODULOS.INVENTARIO_BIENES_VEHICULARES,
    {
      path: ROUTES.INVENTARIO_BIENES_VEHICULARES,
    },
  ],
  [
    IDS_SUBMODULOS.ADMINISTRADOR_CATALOGOS_SIP,
    {
      path: ROUTES.ADMINISTRADOR_CATALOGOS_SIP,
    },
  ],
  [
    IDS_SUBMODULOS.DEPRECIACION,
    {
      path: ROUTES.DEPRECIACION,
    },
  ],
  [
    IDS_SUBMODULOS.ENTRADAS_SALIDAS,
    {
      path: ROUTES.ENTRADAS_SALIDAS,
    },
  ],
  [
    IDS_SUBMODULOS.INVENTARIO_ALMACENES,
    {
      path: ROUTES.INVENTARIO_ALMACEN,
    },
  ],
  [
    IDS_SUBMODULOS.ADMINISTRADOR_CATALOGOS_SIA,
    {
      path: ROUTES.ADMINISTRADOR_CATALOGOS_SIA,
    },
  ],
  [
    IDS_SUBMODULOS.ADMINISTRADOR_EMPLEADOS_USUARIOS,
    {
      path: ROUTES.ADMINISTRADOR_EMPLEADOS_USUARIOS,
    },
  ],
]);
