import { ROUTES } from "./routeConfig";

export const CLAVE_TOKEN = "auth_token";

export const IDS_SECCIONES = {
  MENU_PRINCIPAL: 1,
  CATALOGOS: 2,
};

export const IDS_MODULOS = {
  SEGURIDAD: 1,
  PATRIMONIO: 2,
  ALMACEN: 3,
};

export const IDS_SUBMODULOS = {
  INCIO: -1,
  MENU: 0,
  ADMINISTRADOR_CEDULAS_BIENES_MUEBLES: 1,
  ADMINISTRADOR_CEDULAS_BIENES_INMUEBLES: 2,
  ADMINISTRADOR_CEDULAS_BIENES_VEHICULARES: 3,
  INVENTARIO_BIENES_MUEBLES: 4,
  INVENTARIO_BIENES_INMUEBLES: 5,
  INVENTARIO_BIENES_VEHICULARES: 6,
  ADMINISTRADOR_CATALOGOS_SIP: 7,
  CATALOGO_TIPO_BIENES_INMUEBLES: 8,
  ENTRADAS_SALIDAS: 9,
  INVENTARIO_ALMACENES: 10,
  ADMINISTRADOR_CATALOGOS_SIA: 11,
  ADMINISTRADOR_EMPLEADOS_USUARIOS: 13,
  DEPRECIACION: 12,
  PERFIL: 14,
};

export const navInfoInicioConfig = {
  idSubModulo: IDS_SUBMODULOS.INCIO,
  nombre: "Inicio SICBA",
  abreviacion: "MI",
  modulo: "Módulo de Inicio",
};

export const modulosConfig = new Map([
  [
    IDS_MODULOS.SEGURIDAD,
    {
      path: ROUTES.MENU_SEGURIDAD,
    },
  ],
  [
    IDS_MODULOS.PATRIMONIO,
    {
      path: ROUTES.MENU_PATRIMONIO,
    },
  ],
  [
    IDS_MODULOS.ALMACEN,
    {
      path: ROUTES.MENU_ALMANCEN,
    },
  ],
]);

export const subModulosConfig = new Map([
  [
    IDS_SUBMODULOS.ADMINISTRADOR_CEDULAS_BIENES_MUEBLES,
    {
      path: ROUTES.ADMINISTRADOR_CATALOGOS_SIP,
    },
  ],
  [
    IDS_SUBMODULOS.ADMINISTRADOR_CEDULAS_BIENES_INMUEBLES,
    {
      path: ROUTES.ADMINISTRADOR_CATALOGOS_SIP,
    },
  ],
  [
    IDS_SUBMODULOS.ADMINISTRADOR_CEDULAS_BIENES_VEHICULARES,
    {
      path: ROUTES.ADMINISTRADOR_CATALOGOS_SIP,
    },
  ],
  [
    IDS_SUBMODULOS.INVENTARIO_BIENES_MUEBLES,
    {
      path: ROUTES.ADMINISTRADOR_CATALOGOS_SIP,
    },
  ],
  [
    IDS_SUBMODULOS.INVENTARIO_BIENES_INMUEBLES,
    {
      path: ROUTES.ADMINISTRADOR_CATALOGOS_SIP,
    },
  ],
  [
    IDS_SUBMODULOS.INVENTARIO_BIENES_VEHICULARES,
    {
      path: ROUTES.ADMINISTRADOR_CATALOGOS_SIP,
    },
  ],
  [
    IDS_SUBMODULOS.ADMINISTRADOR_CATALOGOS_SIP,
    {
      path: ROUTES.ADMINISTRADOR_CATALOGOS_SIP,
    },
  ],
  [
    IDS_SUBMODULOS.CATALOGO_TIPO_BIENES_INMUEBLES,
    {
      path: ROUTES.ADMINISTRADOR_CATALOGOS_SIP,
    },
  ],
  [
    IDS_SUBMODULOS.ENTRADAS_SALIDAS,
    {
      path: ROUTES.ADMINISTRADOR_CATALOGOS_SIP,
    },
  ],
  [
    IDS_SUBMODULOS.INVENTARIO_ALMACENES,
    {
      path: ROUTES.ADMINISTRADOR_CATALOGOS_SIP,
    },
  ],
  [
    IDS_SUBMODULOS.ADMINISTRADOR_CATALOGOS_SIA,
    {
      path: ROUTES.ADMINISTRADOR_CATALOGOS_SIA,
    },
  ],
  [
    IDS_SUBMODULOS.ADMINISTRADOR_EMPLEADOS_USUARIOS,
    {
      path: ROUTES.ADMINISTRADOR_EMPLEADOS_USUARIOS,
    },
  ],
]);
